version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: postres-db
    environment:
      POSTGRES_DB: socialfeeds
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
